"""add user model

Revision ID: 2e57e9383494
Revises: 1ed19c761a2d
Create Date: 2025-08-06 16:23:37.822953

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "2e57e9383494"
down_revision: str | Sequence[str] | None = "1ed19c761a2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	pass
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	pass
	# ### end Alembic commands ###
