"""add more fields

Revision ID: 304eabd534a4
Revises: 8dd0f90acfd3
Create Date: 2025-08-08 20:45:14.194149

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "304eabd534a4"
down_revision: str | Sequence[str] | None = "8dd0f90acfd3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column("tasks", "task_list_id", existing_type=sa.UUID(), nullable=True)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column("tasks", "task_list_id", existing_type=sa.UUID(), nullable=False)
	# ### end Alembic commands ###
