"""add more fields

Revision ID: 8dd0f90acfd3
Revises: 2e57e9383494
Create Date: 2025-08-08 19:37:09.212812

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8dd0f90acfd3"
down_revision: str | Sequence[str] | None = "2e57e9383494"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column("tasks", sa.Column("title", sa.VARCHAR(length=25), nullable=False))
	op.add_column(
		"tasks", sa.Column("description", sa.VARCHAR(length=255), nullable=True)
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column("tasks", "description")
	op.drop_column("tasks", "title")
	# ### end Alembic commands ###
