http:
  routers:
    prometheus:
      entrypoints:
        - web
      rule: Host(`localhost`)&&PathPrefix(`/prom`)
      service: prometheus

    grafana:
      entrypoints:
        - web
      rule: Host(`localhost`)&&PathPrefix(`/grafana`)
      service: grafana

    crehana:
      entrypoints:
        - web
      rule: Host(`localhost`)&&PathPrefix(`/api/v1/`)
      service: crehana

  services:
    prometheus:
      loadBalancer:
        servers:
          - url: http://prometheus:9090

    grafana:
      loadBalancer:
        servers:
          - url: http://grafana:3000

    crehana:
      loadBalancer:
        servers:
          - url: http://crehana:8000


